import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const panel = await readFile(new URL('../components/index/StatusPanel.vue', import.meta.url), 'utf8')
const center = await readFile(new URL('../components/admin/AuthorizationCenter.vue', import.meta.url), 'utf8')
const audit = await readFile(new URL('../components/admin/AuditLogPanel.vue', import.meta.url), 'utf8')

assert.match(panel, /admin\/authorization\/me/)
assert.match(panel, /isPrimaryAdmin/)
assert.match(panel, /canViewAdminAudit/)
assert.match(panel, /const can = \(capability: string\) => isPrimaryAdmin\.value \|\| adminCapabilities\.value\.includes\(capability\)/)
assert.match(panel, /const canSection = \(section: AdminSectionKey\)/)
assert.match(panel, /items: group\.items\.filter\(\(item\) => canSection\(item\.key\)\)/)
assert.match(panel, /'admin-audit': 'audit\.view'/)
assert.match(panel, /if \(can\('security\.view'\)\) await refreshSecurity\(\)/)
assert.match(panel, /section === 'access-logs' && can\('access_logs\.view'\)/)
assert.match(panel, /section === 'site-visits' && can\('site_visits\.view'\)/)
assert.match(panel, /section === 'login-audits' && can\('login_audits\.view'\)/)
assert.match(panel, /onMounted\(\(\) => \{ if \(can\('notifications\.view'\)\) fetchNotifyConfig\(\) \}\)/)
assert.match(center, /admin\/authorization\/admins/)
assert.match(center, /admin\/authorization\/catalog/)
assert.match(center, /capabilities/)
assert.match(audit, /admin\/audit-logs/)
assert.match(audit, /page_size/)
assert.match(audit, /actor_user_id/)
assert.match(audit, /target_type/)
assert.match(audit, /target_id/)
assert.match(audit, /start/)
assert.match(audit, /end/)
assert.match(audit, /loadDetail/)
assert.match(audit, /admin\/audit-config/)
assert.doesNotMatch(center + audit, /echo-noise\s*\/\s*说说笔记/i)
