import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const panel = await readFile(new URL('../components/index/StatusPanel.vue', import.meta.url), 'utf8')
const capabilities = await readFile(new URL('../composables/useAdminCapabilities.ts', import.meta.url), 'utf8')
const center = await readFile(new URL('../components/admin/AuthorizationCenter.vue', import.meta.url), 'utf8')
const audit = await readFile(new URL('../components/admin/AuditLogPanel.vue', import.meta.url), 'utf8')

assert.match(capabilities, /admin\/authorization\/me/)
assert.match(panel, /useAdminCapabilities\(\)/)
assert.match(panel, /isPrimaryAdmin/)
assert.match(panel, /canViewAdminAudit/)
assert.match(capabilities, /const can = \(capability: string\) => isPrimaryAdmin\.value \|\|/)
assert.match(panel, /const canSection = \(section: AdminSectionKey\)/)
assert.match(panel, /items: group\.items\.filter\(\(item\) => canSection\(item\.key\)\)/)
assert.match(panel, /'admin-audit': 'audit\.view'/)
assert.match(panel, /if \(can\('security\.view'\)\) await refreshSecurity\(\)/)
assert.match(panel, /section === 'access-logs' && can\('access_logs\.view'\)/)
assert.match(panel, /section === 'site-visits' && can\('site_visits\.view'\)/)
assert.match(panel, /section === 'login-audits' && can\('login_audits\.view'\)/)
assert.match(panel, /onMounted\(\(\) => \{ if \(can\('notifications\.view'\)\) fetchNotifyConfig\(\) \}\)/)
assert.match(center, /admin\/authorization\/admins/)
assert.match(center, /admin\/authorization\/catalog/)
assert.match(center, /capabilities/)
assert.match(audit, /admin\/audit-logs/)
assert.match(audit, /page_size/)
assert.match(audit, /actor_user_id/)
assert.match(audit, /target_type/)
assert.match(audit, /target_id/)
assert.match(audit, /start/)
assert.match(audit, /end/)
assert.match(audit, /loadDetail/)
assert.match(audit, /admin\/audit-config/)
assert.match(audit, /operation_description/)
assert.match(audit, /result_description/)
assert.match(audit, /reason_description/)
assert.match(audit, /const buildAuditQuery/)
assert.match(audit, /buildAuditQuery\(true\)/)
assert.match(audit, /buildAuditQuery\(false\)/)
assert.match(audit, /admin\/audit-logs\/export/)
assert.match(audit, /exporting/)
assert.match(audit, /Content-Disposition/)
assert.match(audit, /导出当前筛选结果/)
assert.match(audit, /导出审计失败/)
assert.match(
  panel,
  /\.admin-form-shell\s*:deep\(input:not\(\[type="checkbox"\]\):not\(\[type="radio"\]\)\),[\s\S]*?min-height:\s*38px/,
  'the admin form field rule must exclude checkboxes and radios so delegated-capability controls stay square and clickable'
)
assert.doesNotMatch(center + audit, /echo-noise\s*\/\s*说说笔记/i)
