import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const panel = await readFile(new URL('../components/index/StatusPanel.vue', import.meta.url), 'utf8')
const capabilities = await readFile(new URL('../composables/useAdminCapabilities.ts', import.meta.url), 'utf8')
const sectionCapabilities = JSON.parse(await readFile(new URL('../config/admin-section-capabilities.json', import.meta.url), 'utf8'))
const center = await readFile(new URL('../components/admin/AuthorizationCenter.vue', import.meta.url), 'utf8')
const audit = await readFile(new URL('../components/admin/AuditLogPanel.vue', import.meta.url), 'utf8')
const moduleHeader = await readFile(new URL('../components/admin/AdminModuleHeader.vue', import.meta.url), 'utf8').catch(() => '')

assert.match(capabilities, /admin\/authorization\/me/)
assert.match(capabilities, /getRequest\('admin\/authorization\/me'/, 'capability snapshots must use the shared Bearer-aware request adapter')
assert.doesNotMatch(center, /\bfetch\(/, 'the authorization center must not use a session-only bare fetch path')
assert.match(center, /getRequest\('admin\/authorization\/catalog'/)
assert.match(center, /putRequest\(`admin\/authorization\/admins\/\$\{selectedID\.value\}`/)
assert.match(panel, /useAdminCapabilities\(\)/)
assert.match(panel, /isPrimaryAdmin/)
assert.match(panel, /canViewAdminAudit/)
assert.match(capabilities, /const can = \(capability: string\) => isPrimaryAdmin\.value \|\|/)
assert.match(panel, /const canSection = \(section: AdminSectionKey\)/)
assert.match(panel, /items: group\.items\.filter\(\(item\) => canSection\(item\.key\)\)/)
assert.equal(sectionCapabilities['admin-audit'], 'audit.view')
assert.match(panel, /if \(can\('security\.view'\)\) await refreshSecurity\(\)/)
assert.match(panel, /section === 'access-logs' && can\('access_logs\.view'\)/)
assert.match(panel, /section === 'site-visits' && can\('site_visits\.view'\)/)
assert.match(panel, /section === 'login-audits' && can\('login_audits\.view'\)/)
assert.match(panel, /onMounted\(\(\) => \{ if \(can\('notifications\.view'\)\) fetchNotifyConfig\(\) \}\)/)
assert.match(center, /admin\/authorization\/admins/)
assert.match(center, /admin\/authorization\/catalog/)
assert.match(center, /capabilities/)
assert.match(center, /parent_capability/, 'authorization catalog items must expose their parent capability')
assert.match(center, /flattenCapabilityTree/, 'authorization modules must render parent permissions before descendants at every depth')
assert.match(center, /group\.rendered/, 'authorization modules must use the complete flattened capability tree')
assert.match(center, /parentSelected\(item\)/, 'child controls must remain locked until their parent is selected')
assert.match(center, /removeDescendants\(capabilities, capability\)/, 'revoking a parent must revoke its child permissions in the pending grant set')
assert.match(center, /notes\.view_hidden/, 'note hidden-read must be a scoped capability')
assert.match(center, /comments\.view_hidden/, 'interaction hidden-read must be a scoped capability')
assert.doesNotMatch(center, /content\.view_hidden/, 'the legacy cross-domain hidden-read capability must not remain in the panel')
assert.match(center, /AdminModuleHeader/, 'authorization must use the shared admin module header')
assert.match(audit, /AdminModuleHeader/, 'audit must use the shared admin module header')
assert.match(audit, /audit-filter-card/, 'audit filters must use the same card hierarchy as note management')
assert.match(audit, /audit-table-shell/, 'audit records must use the same table shell hierarchy as note management')
assert.match(moduleHeader, /text-base/, 'all target panels must share one fixed title size')
assert.match(panel, /AdminAuditLogPanel :is-primary-admin="isPrimaryAdmin" :theme="theme"/, 'audit must receive the active admin theme')
assert.match(audit, /admin\/audit-logs/)
assert.match(audit, /page_size/)
assert.match(audit, /actor_user_id/)
assert.match(audit, /target_type/)
assert.match(audit, /target_id/)
assert.match(audit, /start/)
assert.match(audit, /end/)
assert.match(audit, /loadDetail/)
assert.match(audit, /admin\/audit-config/)
assert.match(audit, /operation_description/)
assert.match(audit, /result_description/)
assert.match(audit, /reason_description/)
assert.match(audit, /item\.safe_summary \|\| '管理员操作摘要'/, 'audit list must render the backend-safe Chinese summary instead of the raw technical summary')
assert.match(audit, /detail\.safe_summary \|\| '管理员操作摘要'/, 'audit details must render the backend-safe Chinese summary instead of the raw technical summary')
assert.match(audit, /const buildAuditQuery/)
assert.match(audit, /buildAuditQuery\(true\)/)
assert.match(audit, /buildAuditQuery\(false\)/)
assert.match(audit, /admin\/audit-logs\/export/)
assert.match(audit, /exporting/)
assert.match(audit, /Content-Disposition/)
assert.match(audit, /导出当前筛选结果/)
assert.match(audit, /导出审计失败/)
assert.match(
  panel,
  /\.admin-form-shell\s*:deep\(input:not\(\[type="checkbox"\]\):not\(\[type="radio"\]\)\),[\s\S]*?min-height:\s*38px/,
  'the admin form field rule must exclude checkboxes and radios so delegated-capability controls stay square and clickable'
)
assert.doesNotMatch(center + audit, /echo-noise\s*\/\s*说说笔记/i)
