import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const messageList = await readFile(new URL('../components/index/MessageList.vue', import.meta.url), 'utf8')
const addForm = await readFile(new URL('../components/index/AddForm.vue', import.meta.url), 'utf8')
const capabilityModule = await readFile(new URL('../composables/useAdminCapabilities.ts', import.meta.url), 'utf8')
const statusPanel = await readFile(new URL('../components/index/StatusPanel.vue', import.meta.url), 'utf8')
const homePage = await readFile(new URL('../pages/index.vue', import.meta.url), 'utf8')

assert.match(capabilityModule, /export const useAdminCapabilities = \(\)/, 'homepage and admin panel must share one capability module')
assert.match(capabilityModule, /admin\/authorization\/me/, 'capabilities must come from the server-authoritative snapshot')
assert.match(capabilityModule, /const can = \(capability: string\) => isPrimaryAdmin\.value \|\|/, 'the shared module must expose a single capability check')
assert.match(statusPanel, /useAdminCapabilities\(\)/, 'admin navigation must consume the shared capability module')
assert.match(messageList, /useAdminCapabilities\(\)/, 'homepage management controls must consume the shared capability module')
assert.match(messageList, /<button v-if="canEdit\(msg\)"[\s\S]*?@click="editMessage\(msg\)"/, 'edit button must be hidden when the actor cannot edit the note')
assert.match(messageList, /<button v-if="canDelete\(msg\)"[\s\S]*?@click="deleteMsg\(msg\)"/, 'delete button must be hidden when the actor cannot delete the note')
assert.match(messageList, /const canManageOtherMessage = \(msg: any, capability: string\) =>[\s\S]*?can\(capability\)/, 'cross-owner controls must delegate to the shared capability check')
assert.match(messageList, /const canGlobalPin = \(msg: any\) =>[\s\S]*?can\('notes\.pin_global'\)/, 'global pinning must require notes.pin_global')
assert.match(messageList, /const canPin = \(msg: any\) =>[\s\S]*?pinScope\.value === 'personal'[\s\S]*?canGlobalPin\(msg\)/, 'pin controls must switch between personal ownership and global capability rules')
assert.match(messageList, /const canEdit = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.edit'\)/, 'cross-owner editing must require notes.edit')
assert.match(messageList, /const canDelete = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.trash'\)/, 'cross-owner deletion must use the move-to-recycle-bin capability')
assert.match(messageList, /const canInteractWithMessage = \(msg: any\) => msg\?\.can_interact === true/, 'interaction controls must consume the server-authoritative normal-visibility decision')
const notificationCenter = await readFile(new URL('../components/index/UserNotificationCenter.vue', import.meta.url), 'utf8')
assert.match(notificationCenter, /can-interact="item\.message\?\.can_interact === true"/, 'notification replies must consume the server-authoritative interaction decision')
assert.match(notificationCenter, /item\.message\?\.can_interact === true/, 'notification reply button must be hidden for non-interactable messages')
assert.match(messageList, /const canGlobalPin = \(msg: any\) =>[\s\S]*?canInteractWithMessage\(msg\)[\s\S]*?can\('notes\.pin_global'\)/, 'global pinning must require both normal visibility and notes.pin_global')
assert.match(messageList, /const canEditMessageTasks = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.edit'\)/, 'task editing must follow note-edit capability')
assert.match(messageList, /const canEditPublishTime = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.change_publish_time'\)/, 'publish-time control must follow notes.change_publish_time')
assert.match(messageList, /const canChangeVisibility = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.change_visibility'\)/, 'visibility control must follow notes.change_visibility')
assert.match(messageList, /if \(!canDelete\(msg\)\) return/, 'delete command must retain the same client-side guard as its button')
assert.match(messageList, /if \(!canPin\(msg\)\) return/, 'pin command must retain the same client-side guard as its button')
assert.match(addForm, /useAdminCapabilities\(\)/, 'publish controls must consume the shared capability module')
assert.match(addForm, /const canNotify = computed\(\(\) => can\('notifications\.manage'\)\)/, 'publish notification control must require notifications.manage')
assert.match(addForm, /const canSetPublishTime = computed\(\(\) => can\('notes\.change_publish_time'\)\)/, 'custom publish time must require notes.change_publish_time')
assert.doesNotMatch(homePage, /v-if="can\('feed\.manage'\)"/, 'feed refresh must be available to every visitor')
assert.doesNotMatch(homePage, /const refreshInfoFeed = async \(\) => \{[\s\S]*?if \(!can\('feed\.manage'\)\) return/, 'public feed refresh must not retain an administrator-only client guard')
