import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const messageList = await readFile(new URL('../components/index/MessageList.vue', import.meta.url), 'utf8')
const addForm = await readFile(new URL('../components/index/AddForm.vue', import.meta.url), 'utf8')
const capabilityModule = await readFile(new URL('../composables/useAdminCapabilities.ts', import.meta.url), 'utf8')
const statusPanel = await readFile(new URL('../components/index/StatusPanel.vue', import.meta.url), 'utf8')
const homePage = await readFile(new URL('../pages/index.vue', import.meta.url), 'utf8')

assert.match(capabilityModule, /export const useAdminCapabilities = \(\)/, 'homepage and admin panel must share one capability module')
assert.match(capabilityModule, /admin\/authorization\/me/, 'capabilities must come from the server-authoritative snapshot')
assert.match(capabilityModule, /const can = \(capability: string\) => isPrimaryAdmin\.value \|\|/, 'the shared module must expose a single capability check')
assert.match(statusPanel, /useAdminCapabilities\(\)/, 'admin navigation must consume the shared capability module')
assert.match(messageList, /useAdminCapabilities\(\)/, 'homepage management controls must consume the shared capability module')
assert.match(messageList, /<button v-if="canEdit\(msg\)"[\s\S]*?@click="editMessage\(msg\)"/, 'edit button must be hidden when the actor cannot edit the note')
assert.match(messageList, /<button v-if="canDelete\(msg\)"[\s\S]*?@click="deleteMsg\(msg\)"/, 'delete button must be hidden when the actor cannot delete the note')
assert.match(messageList, /const canManageOtherMessage = \(msg: any, capability: string\) =>[\s\S]*?can\(capability\)/, 'cross-owner controls must delegate to the shared capability check')
assert.match(messageList, /const canPin = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.pin_global'\)/, 'cross-owner pinning must require notes.pin_global')
assert.match(messageList, /const canEdit = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.edit'\)/, 'cross-owner editing must require notes.edit')
assert.match(messageList, /const canDelete = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.delete_permanently'\)/, 'cross-owner deletion must require notes.delete_permanently')
assert.match(messageList, /const canEditMessageTasks = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.edit'\)/, 'task editing must follow note-edit capability')
assert.match(messageList, /const canEditPublishTime = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.change_publish_time'\)/, 'publish-time control must follow notes.change_publish_time')
assert.match(messageList, /const canChangeVisibility = \(msg: any\) =>[\s\S]*?canManageOtherMessage\(msg, 'notes\.change_visibility'\)/, 'visibility control must follow notes.change_visibility')
assert.match(messageList, /if \(!canDelete\(msg\)\) return/, 'delete command must retain the same client-side guard as its button')
assert.match(messageList, /if \(!canPin\(msg\)\) return/, 'pin command must retain the same client-side guard as its button')
assert.match(addForm, /useAdminCapabilities\(\)/, 'publish controls must consume the shared capability module')
assert.match(addForm, /const canNotify = computed\(\(\) => can\('notifications\.manage'\)\)/, 'publish notification control must require notifications.manage')
assert.match(addForm, /const canSetPublishTime = computed\(\(\) => can\('notes\.change_publish_time'\)\)/, 'custom publish time must require notes.change_publish_time')
assert.match(homePage, /useAdminCapabilities\(\)/, 'feed refresh must consume the shared capability module')
assert.match(homePage, /v-if="can\('feed\.manage'\)"/, 'feed refresh button must require feed.manage')
assert.match(homePage, /const refreshInfoFeed = async \(\) => \{[\s\S]*?if \(!can\('feed\.manage'\)\) return/, 'feed refresh command must retain the same client-side guard as its button')
