import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8')

const model = read('internal/models/models.go')
const lifecycle = read('internal/services/note_lifecycle.go')
const scope = read('internal/services/content_read_scope.go')
const controllers = read('internal/controllers/note_management_controller.go')
const routers = read('internal/routers/routers.go')
const manager = read('web/components/admin/NoteManager.vue')
const moduleHeaderPath = path.join(root, 'web/components/admin/AdminModuleHeader.vue')
const moduleHeader = fs.existsSync(moduleHeaderPath) ? fs.readFileSync(moduleHeaderPath, 'utf8') : ''
const panel = read('web/components/index/StatusPanel.vue')
const capabilities = JSON.parse(read('web/config/admin-section-capabilities.json'))
const confirmation = await import('../utils/note-lifecycle-confirmation.ts')

assert.match(model, /DeletedAt\s+\*time\.Time/)
assert.match(model, /DeletedByUserID\s+\*uint/)
assert.match(model, /DeletedReason\s+string/)
assert.match(lifecycle, /func TrashMessage\(/)
assert.match(lifecycle, /func RestoreMessage\(/)
assert.match(lifecycle, /func PermanentlyDeleteMessage\(/)
assert.match(lifecycle, /deleted_at IS NOT NULL/)
assert.doesNotMatch(lifecycle, /PurgeBlob|DeleteReference/)
assert.doesNotMatch(lifecycle, /UserNotification/)
assert.match(scope, /ApplyMessageVisibilityIncludingDeleted/)
assert.match(scope, /deleted_at IS NULL/)
assert.match(controllers, /func ListAdminNotes\(/)
assert.match(controllers, /func ListAdminRecycleBin\(/)
assert.match(controllers, /func BatchPermanentDeleteAdminRecycleBin\(/)
assert.match(routers, /CapabilityNotesView/)
assert.match(routers, /CapabilityNotesRecycleBinView/)
assert.match(routers, /BatchPermanentDeleteAdminRecycleBin/)
assert.equal(capabilities.notes, 'notes.view')
assert.equal(capabilities['recycle-bin'], 'notes.recycle_bin.view')
assert.match(manager, /可勾选当前页笔记，或主动选择当前筛选结果/)
assert.match(manager, /永久删除所选/)
assert.match(manager, /admin\/recycle-bin/)
assert.match(manager, /can\('notes\.trash'\)/)
assert.match(manager, /can\('notes\.restore'\)/)
assert.match(manager, /can\('notes\.delete_permanently'\)/)
assert.match(manager, /runConfirmedFilteredLifecycle\('trash', total\.value/)
assert.match(manager, /runConfirmedFilteredLifecycle\('restore', total\.value/)
assert.match(manager, /runConfirmedFilteredLifecycle\('permanent-delete', total\.value/)
assert.match(manager, /title: '操作失败'/)
assert.match(manager, /AdminModuleHeader/, 'note management and recycle bin must use the shared admin module header')
assert.match(manager, /class="note-content\s+font-medium"/, 'note excerpts need a dedicated constrained content box')
assert.match(manager, /table-fixed/, 'note columns need a deterministic width budget')
assert.match(manager, /overflow-wrap:\s*anywhere/, 'unbroken URLs and attachment paths must wrap inside the note column')
assert.match(moduleHeader, /admin-module-title/, 'shared module header must own the title typography')
assert.match(moduleHeader, /admin-module-icon/, 'shared module header must own the icon treatment')
assert.match(panel, /NoteManager/)
assert.match(panel, /recycle-bin/)

assert.equal(confirmation.filteredLifecycleConfirmationMessage('trash', 40), '将把当前筛选结果中的 40 条笔记移入回收站，是否继续？')
assert.equal(confirmation.filteredLifecycleConfirmationMessage('restore', 40), '将恢复当前筛选结果中的 40 条笔记，是否继续？')
assert.equal(confirmation.filteredLifecycleConfirmationMessage('permanent-delete', 40), '将永久删除当前筛选结果中的 40 条回收站笔记，且不可恢复。是否继续？')
let requests = 0
await confirmation.runConfirmedFilteredLifecycle('trash', 40, () => false, async () => { requests += 1 })
assert.equal(requests, 0, 'cancelling filtered lifecycle confirmation must not send a request')
await confirmation.runConfirmedFilteredLifecycle('restore', 40, () => true, async () => { requests += 1 })
assert.equal(requests, 1, 'accepting filtered lifecycle confirmation sends exactly one request')

console.log('note management contract tests passed')
