<template>
  <section id="security-section" :class="adminShellCardClass">
    <AdminModuleHeader title="安全防护" icon="i-heroicons-shield-exclamation" description="管理访问防护规则并查看攻击记录。" :theme="theme"><template #actions><div class="flex flex-wrap items-center gap-2"><UButton icon="i-heroicons-arrow-path" size="sm" color="gray" variant="soft" class="admin-action" @click="loadAll">刷新</UButton><UButton v-if="can('security.clear_logs')" size="sm" color="red" variant="soft" class="admin-action" @click="clearAttackLogs">清空攻击记录</UButton></div></template></AdminModuleHeader>
    <div class="px-4 pb-4 admin-page-body">
      <div class="admin-settings-grid">
        <section class="admin-form-section admin-security-policy">
          <div class="admin-settings-toolbar flex flex-wrap items-center justify-between gap-2 mb-2"><div class="font-semibold" :class="theme.text">自动封禁策略</div><div class="flex items-center gap-3"><div class="admin-security-toggle"><span :class="theme.mutedText">启用自动封禁</span><UToggle v-model="config.autoBanEnabled" :disabled="!can('security.manage')" /></div><UButton v-if="can('security.manage')" size="sm" color="primary" class="admin-action" @click="savePolicy">保存策略</UButton></div></div>
          <div class="admin-fields-grid"><label class="admin-labeled-field"><span>统计窗口（秒）</span><UInput class="admin-input" v-model.number="config.autoBanWindowSeconds" type="number" :disabled="!can('security.manage')" /></label><label class="admin-labeled-field"><span>触发次数（窗口内）</span><UInput class="admin-input" v-model.number="config.autoBanThreshold" type="number" :disabled="!can('security.manage')" /></label><label class="admin-labeled-field"><span>封禁时长（分钟，0=永久）</span><UInput class="admin-input" v-model.number="config.autoBanMinutes" type="number" :disabled="!can('security.manage')" /></label><label class="admin-labeled-field"><span>攻击记录保留期限</span><USelect class="admin-select" v-model="config.attackLogRetentionDays" :options="retentionOptions" :disabled="!can('security.manage')" /></label></div>
          <div class="text-xs mt-2" :class="theme.mutedText">仅对敏感路径扫描命中进行计数；达到阈值后将自动写入封禁列表并立即生效</div>
        </section>
        <div v-if="isPrimaryAdmin" class="admin-setting-stack">
          <section id="site-login-expire-section" class="admin-form-section admin-expiry-settings" :class="adminSubtleCardClass"><div class="admin-settings-toolbar flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3"><div class="font-semibold" :class="theme.text">普通用户登录过期时间</div><div class="flex flex-wrap items-center gap-2"><UInput v-model.number="loginExpiry.days" type="number" min="0" max="31" class="admin-input w-24" /><span :class="theme.mutedText">天</span><UInput v-model.number="loginExpiry.hours" type="number" min="0" max="24" class="admin-input w-24" /><span :class="theme.mutedText">小时</span><UButton v-for="preset in expiryPresets" :key="preset.label" size="sm" color="gray" variant="soft" class="admin-action" @click="setExpiry(preset)">{{ preset.label }}</UButton><UButton size="sm" color="primary" class="admin-action" @click="saveExpiry">保存</UButton></div></div><div class="text-xs mt-2" :class="theme.mutedText">普通用户从登录那一刻开始计算；0 天 0 小时表示永久不过期。站长默认永不过期。</div></section>
          <section id="site-delegated-admin-login-expire-section" class="admin-form-section admin-expiry-settings" :class="adminSubtleCardClass"><div class="admin-settings-toolbar flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3"><div class="font-semibold" :class="theme.text">受托管理员登录过期时间</div><div class="flex flex-wrap items-center gap-2"><UInput v-model.number="delegatedExpiry.days" type="number" min="0" max="31" class="admin-input w-24" /><span :class="theme.mutedText">天</span><UInput v-model.number="delegatedExpiry.hours" type="number" min="0" max="24" class="admin-input w-24" /><span :class="theme.mutedText">小时</span><UButton v-for="preset in expiryPresets" :key="preset.label" size="sm" color="gray" variant="soft" class="admin-action" @click="setExpiry(preset, true)">{{ preset.label }}</UButton><UButton size="sm" color="primary" class="admin-action" @click="saveExpiry">保存</UButton></div></div><div class="text-xs mt-2" :class="theme.mutedText">仅受托管理员按此有效期计算，Session 与管理员 Bearer 同步生效；0 天 0 小时表示永久不过期。站长默认永不过期。</div></section>
        </div>
      </div>
      <div class="admin-security-records">
        <section class="admin-record-panel"><div class="font-semibold mb-2" :class="theme.text">攻击记录（最近 {{ attacks.length }} 条）</div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr :class="theme.mutedText"><th class="text-left py-2 pr-4">时间</th><th class="text-left py-2 pr-4">IP</th><th class="text-left py-2 pr-4">方法</th><th class="text-left py-2 pr-4">路径</th><th class="text-left py-2">操作</th></tr></thead><tbody><tr v-for="(row, index) in attacks" :key="row.ID ?? row.id ?? index" class="border-t" :class="theme.border"><td class="py-2 pr-4" :class="theme.mutedText">{{ formatShanghai(row.created_at || row.CreatedAt) }}</td><td class="py-2 pr-4 font-mono" :class="theme.text">{{ row.ip || row.IP }}</td><td class="py-2 pr-4" :class="theme.mutedText">{{ row.method || row.Method }}</td><td class="py-2 pr-4 break-all" :class="theme.text">{{ row.path || row.Path }}</td><td class="py-2"><div class="flex gap-2"><UButton size="sm" color="orange" variant="soft" class="admin-action" @click="prepareBan(row.ip || row.IP)">封禁</UButton><UButton v-if="can('security.clear_logs')" size="sm" color="red" variant="soft" class="admin-action" :loading="deletingAttackID === (row.ID ?? row.id)" @click="deleteAttack(row)">删除</UButton></div></td></tr><tr v-if="!attacks.length"><td colspan="5" class="py-3" :class="theme.mutedText">暂无记录</td></tr></tbody></table></div></section>
        <section class="admin-record-panel"><div class="admin-settings-toolbar flex flex-wrap items-center justify-between gap-3 mb-2"><div class="font-semibold" :class="theme.text">封禁 IP</div><div class="flex flex-wrap items-center gap-2"><UInput v-model="banForm.ip" placeholder="IP" class="admin-input w-40" /><UInput v-model.number="banForm.minutes" type="number" placeholder="分钟(0=永久)" class="admin-input w-36" /><UInput v-model="banForm.reason" placeholder="原因(可选)" class="admin-input w-56" /><UButton size="sm" color="orange" class="admin-action" @click="submitBan">封禁</UButton></div></div><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead><tr :class="theme.mutedText"><th class="text-left py-2 pr-4">IP</th><th class="text-left py-2 pr-4">原因</th><th class="text-left py-2 pr-4">到期</th><th class="text-left py-2">操作</th></tr></thead><tbody><tr v-for="(ban, index) in bans" :key="ban.ID ?? ban.id ?? index" class="border-t" :class="theme.border"><td class="py-2 pr-4 font-mono" :class="theme.text">{{ ban.ip || ban.IP }}</td><td class="py-2 pr-4" :class="theme.mutedText">{{ ban.reason || ban.Reason || '-' }}</td><td class="py-2 pr-4" :class="theme.mutedText">{{ ban.until || ban.Until ? formatShanghai(ban.until || ban.Until) : '永久' }}</td><td class="py-2"><UButton size="sm" color="primary" variant="soft" class="admin-action" @click="unban(ban.ip || ban.IP)">解封</UButton></td></tr><tr v-if="!bans.length"><td colspan="4" class="py-3" :class="theme.mutedText">暂无封禁</td></tr></tbody></table></div></section>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { deleteRequest, getRequest, postRequest } from '~/utils/api'
import { useToast } from '#ui/composables/useToast'
import { useAdminCapabilities } from '~/composables/useAdminCapabilities'
import { loadFrontendSettings, saveFrontendSettings } from './frontend-settings'
import { formatShanghai, loadSecurityConfig, retentionOptions, saveSecurityConfig, securityConfigDefaults } from './security-config'

const props = defineProps<{ theme: any, adminShellCardClass: any, adminSubtleCardClass: any }>()
const theme = props.theme
const adminShellCardClass = props.adminShellCardClass
const adminSubtleCardClass = props.adminSubtleCardClass
const { can, isPrimaryAdmin } = useAdminCapabilities()
const config = reactive({ ...securityConfigDefaults })
const attacks = ref<any[]>([])
const bans = ref<any[]>([])
const deletingAttackID = ref<number | null>(null)
const banForm = reactive({ ip: '', minutes: 0, reason: '' })
const loginExpiry = reactive({ days: 3, hours: 0 })
const delegatedExpiry = reactive({ days: 3, hours: 0 })
const expiryPresets = [{ label: '永久', days: 0, hours: 0 }, { label: '1 天', days: 1, hours: 0 }, { label: '3 天', days: 3, hours: 0 }, { label: '7 天', days: 7, hours: 0 }]
const setExpiry = (preset: any, delegated = false) => Object.assign(delegated ? delegatedExpiry : loginExpiry, { days: preset.days, hours: preset.hours })
const normalizeExpiry = (value: { days: number, hours: number }) => { let total = Math.max(0, Math.round(Number(value.days || 0) * 24 + Number(value.hours || 0))); return { days: Math.floor(total / 24), hours: total % 24 } }
const loadExpiry = async () => { if (!isPrimaryAdmin.value) return; const settings = (await loadFrontendSettings()).frontendSettings; Object.assign(loginExpiry, normalizeExpiry({ days: settings.loginExpireDays ?? 3, hours: settings.loginExpireHours ?? 0 })); Object.assign(delegatedExpiry, normalizeExpiry({ days: settings.delegatedAdminLoginExpireDays ?? 3, hours: settings.delegatedAdminLoginExpireHours ?? 0 })) }
const saveExpiry = async () => { try { const user = normalizeExpiry(loginExpiry); const delegated = normalizeExpiry(delegatedExpiry); await saveFrontendSettings({ loginExpireDays: user.days, loginExpireHours: user.hours, delegatedAdminLoginExpireDays: delegated.days, delegatedAdminLoginExpireHours: delegated.hours }); Object.assign(loginExpiry, user); Object.assign(delegatedExpiry, delegated); useToast().add({ title: '登录有效期已保存', color: 'green' }) } catch (error: any) { useToast().add({ title: '保存失败', description: error?.message, color: 'red' }) } }
const loadAll = async () => { try { const [security, attackResponse, banResponse]: any[] = await Promise.all([loadSecurityConfig(), getRequest<any>('security/attacks', { limit: 200 }, { credentials: 'include', silent: true }), getRequest<any>('security/bans', undefined, { credentials: 'include', silent: true })]); Object.assign(config, security); attacks.value = attackResponse?.code === 1 && Array.isArray(attackResponse.data) ? attackResponse.data : []; bans.value = banResponse?.code === 1 && Array.isArray(banResponse.data) ? banResponse.data : [] } catch (error: any) { useToast().add({ title: '加载安全信息失败', description: error?.message, color: 'red' }) } }
const savePolicy = async () => { try { const response: any = await saveSecurityConfig(config); useToast().add({ title: response?.msg || '已保存', color: 'green' }); await loadAll() } catch (error: any) { useToast().add({ title: '保存失败', description: error?.message, color: 'red' }) } }
const clearAttackLogs = async () => { if (!window.confirm('确定清空所有攻击记录吗？')) return; try { const response: any = await deleteRequest<any>('security/attacks', undefined, { credentials: 'include' }); if (response?.code !== 1) throw new Error(response?.msg || '清空失败'); await loadAll(); useToast().add({ title: '已清空', color: 'green' }) } catch (error: any) { useToast().add({ title: '操作失败', description: error?.message, color: 'red' }) } }
const deleteAttack = async (row: any) => { const id = Number(row.ID ?? row.id); if (!Number.isSafeInteger(id) || id <= 0 || !window.confirm('确定删除这条攻击记录吗？删除记录不会解除 IP 封禁。')) return; deletingAttackID.value = id; try { const response: any = await deleteRequest<any>(`security/attacks/${id}`, undefined, { credentials: 'include' }); if (response?.code !== 1) throw new Error(response?.msg || '删除失败'); attacks.value = attacks.value.filter(item => Number(item.ID ?? item.id) !== id); useToast().add({ title: '已删除攻击记录', color: 'green' }) } catch (error: any) { useToast().add({ title: '删除失败', description: error?.message, color: 'red' }) } finally { deletingAttackID.value = null } }
const prepareBan = (ip: string) => { banForm.ip = String(ip || '').trim() }
const submitBan = async () => { try { if (!banForm.ip.trim()) throw new Error('请输入IP'); const response: any = await postRequest<any>('security/bans', { ip: banForm.ip.trim(), minutes: Number(banForm.minutes || 0), reason: banForm.reason.trim() }, { credentials: 'include' }); if (response?.code !== 1) throw new Error(response?.msg || '封禁失败'); Object.assign(banForm, { ip: '', minutes: 0, reason: '' }); await loadAll(); useToast().add({ title: '已封禁', color: 'green' }) } catch (error: any) { useToast().add({ title: '封禁失败', description: error?.message, color: 'red' }) } }
const unban = async (ip: string) => { try { const response: any = await deleteRequest<any>('security/bans', { ip: String(ip || '').trim() }, { credentials: 'include' }); if (response?.code !== 1) throw new Error(response?.msg || '解封失败'); await loadAll(); useToast().add({ title: '已解封', color: 'green' }) } catch (error: any) { useToast().add({ title: '解封失败', description: error?.message, color: 'red' }) } }
onMounted(() => Promise.all([loadAll(), loadExpiry()]))
</script>
