<template>
  <section class="admin-setting-block space-y-4"><div class="admin-setting-heading"><div><h2 class="admin-setting-title">管理员审计</h2><p class="admin-setting-desc">只读的管理员操作记录，按最新记录优先显示。</p></div></div><div class="flex flex-wrap gap-2"><UInput v-model="filters.q" placeholder="搜索安全摘要或目标 ID" class="min-w-[220px]" @keyup.enter="load" /><USelect v-model="filters.result" :options="resultOptions" placeholder="全部结果" /><UButton :loading="loading" @click="load">筛选</UButton></div><div class="overflow-x-auto rounded-md border dark:border-gray-700"><table class="min-w-full text-sm"><thead><tr class="text-left"><th class="p-3">时间</th><th class="p-3">操作人</th><th class="p-3">模块/动作</th><th class="p-3">结果</th><th class="p-3">摘要</th></tr></thead><tbody><tr v-for="item in items" :key="item.id" class="border-t dark:border-gray-700"><td class="p-3 whitespace-nowrap">{{ formatTime(item.created_at) }}</td><td class="p-3">{{ item.actor_username }}</td><td class="p-3">{{ item.module }} / {{ item.action }}</td><td class="p-3"><UBadge :color="item.result === 'success' ? 'green' : item.result === 'denied' ? 'yellow' : 'red'">{{ item.result }}</UBadge></td><td class="p-3">{{ item.summary }}</td></tr><tr v-if="!items.length && !loading"><td colspan="5" class="p-5 text-center opacity-70">暂无审计记录。</td></tr></tbody></table></div><div class="flex items-center justify-between"><span class="text-sm opacity-70">共 {{ total }} 条</span><div class="flex gap-2"><UButton size="xs" :disabled="page <= 1 || loading" @click="page--; load()">上一页</UButton><span class="text-sm leading-7">第 {{ page }} 页</span><UButton size="xs" :disabled="items.length < pageSize || loading" @click="page++; load()">下一页</UButton></div></div></section>
</template>
<script setup lang="ts">
type Audit = { id: number, created_at: string, actor_username: string, module: string, action: string, result: 'success'|'denied'|'failure', summary: string }
const items = ref<Audit[]>([]), total = ref(0), page = ref(1), pageSize = 30, loading = ref(false), filters = reactive({ q: '', result: '' })
const resultOptions = [{ label: '全部结果', value: '' }, { label: '成功', value: 'success' }, { label: '拒绝', value: 'denied' }, { label: '失败', value: 'failure' }]
const load = async () => { loading.value = true; try { const query = new URLSearchParams({ page: String(page.value), page_size: String(pageSize) }); if (filters.q.trim()) query.set('q', filters.q.trim()); if (filters.result) query.set('result', filters.result); const response = await fetch(`/api/admin/audit-logs?${query}`, { credentials: 'include' }); const body = await response.json().catch(() => ({})); if (!response.ok || body?.code !== 1) throw new Error(body?.msg || '加载审计失败'); items.value = body.data?.items || []; total.value = body.data?.total || 0 } finally { loading.value = false } }
const formatTime = (value: string) => value ? new Date(value).toLocaleString() : '-'
onMounted(load)
</script>
