server:
  port: "1314"
  host: "0.0.0.0"
  mode: "release" # "release" or "debug"

database:
  type: "sqlite"
  path: "data/noise.db"

upload:
  maxsize: 52428800
  savepath: "data/images/"
  allowedtypes: 
    - "image/jpeg"
    - "image/png"
    - "image/gif"
    - "image/webp"
    - "image/jpg"
    - "video/mp4"
    - "video/webm"
    - "video/quicktime"
    - "video/x-msvideo"

auth:
  jwt:
    secret: "HelloNoise!"
    expires: 2592000 # 30天（单位秒）
    issuer: "noise"
    audience: "noise"
